# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 04:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20161111_0654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-pk']},
        ),
    ]
